### ISSUE TITLE
Entry management system

### ISSUE THREAD

**Issue by thomastanck** [CS2103-AY1819S2-W10-1/main#24]
- [x] As a user I want to be able to quickly search for entries using one or more of the entry fields so that I can navigate a large number of entries more easily (#117)
- [x] As a user I want to archive entries I have read instead of deleting them so that I can still have them saved for future reference (#57, #70)
- [x] As a user I want to be able to switch between my viewing list and archives easily so that I can navigate between them quickly (#71, #79)
- [x] As a user I want to be able to tag my entries so I can search for them quickly (#30)
- [x] As a user I want to add a link with title, preview image and other helpful data automatically extracted and article content downloaded so that I can save it for later reference and view it later when I go offline. (#46)
