### ISSUE TITLE
Reader view

### ISSUE THREAD

**Issue by qjqqyy** [CS2103-AY1819S2-W10-1/main#27]
#### User stories covered:
- [x] As a user, I want to view a saved link in a browser, so that I can read the content of links I've saved.
- [x] As a user, I want to view a saved link in a clean reading mode, so that I can focus on content with no distractions. #45 
- [x] As a heavy user, I want to change the style of reading mode, so that I can choose a style that helps me read a lot of content comfortably. #115 

{ more to be added }
