### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by rlrh** [CS2103-AY1819S2-W10-1/main#28]
As our product's target user personas will be using our app offline, we need to provide our app with offline support.

#### User stories covered
- [x] As an offline user, I can add a link with helpful data to be extracted and article content to be downloaded when connected to the Internet, so that I can save it for later reference. (#46)
- [x] As an offline user, I can view a saved link in a browser while offline, so that I can read the content of links I’ve saved. (#52)
- [x] As an offline user, I can view a saved link in a clean reading mode while offline, so that I can focus on content with no distractions. (#54)
- [x] As a heavy user, I can re-download content from previously saved links, so that I can get the latest revision of content from links I added a long time ago. (#56)
- [x] As a heavy user, I can archive old links and delete their downloaded content, so that I can keep old links for reference but save disk space. (#70)
- [x] As a heavy user, I can import/export data and settings, so that I can transfer my content to another computer. (#58)

**Comment by thomastanck** [comment]
Done!
